version: "3.2"
services:
  postgres:
    container_name: chatter_pg
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatter_dev
    ports:
      - 5432:5432

  